connector_image: airbyte/destination-duckdb:dev
acceptance_tests:
  spec:
    tests:
      - spec_path: integration_tests/spec.json
  connection:
    tests:
      - config_path: "secrets/config.json"
        status: "succeed"
